
---
engines:
  sonarscharp:
    base_sub_dir: "Assets/Scripts"
    exclude_paths:
      - 'Assets/Scripts/SimpleCameraController.cs'
      - 'Assets/SteamVR/**'
exclude_paths:
  - '.github/workflows/**'
  - '.vscode/**'
  - '.codacy.yml'
  - 'Packages/**'
  - 'ProjectSettings/**'
  - 'UserSettings/**'
  - 'Assets/TutorialInfo/**'
  - 'Assets/Shared/**'
  - 'Assets/SteamVR/**
  - 'Assets/ExampleAssets/**'
  - 'Assets/SteamVR_Resources/**
